name: 'Custom Firefox Developer Edition Setup'
description: 'Setup a specific version of Firefox Developer Edition for testing'
inputs:
  gh-access-token:
    description: 'GitHub Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/testsSetup
      with:
        gh-access-token: ${{ inputs.gh-access-token }}
    - uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest-devedition'
